
  CREATE TABLE "SYSTEM"."REVIEWS" 
   (	"HOTEL_ADRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"AVERAGE_SCORE" FLOAT(63) NOT NULL ENABLE, 
	"REVIEW_DATE" DATE NOT NULL ENABLE, 
	"NEGATIVE_REVIEW" VARCHAR2(1500 BYTE), 
	"POSITIVE_REVIEW" VARCHAR2(1500 BYTE), 
	"TOTAL_NUMBER_OF_REVIEWS" NUMBER(*,0) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


  CREATE TABLE "SYSTEM"."HOTEL" 
   (	"HOTEL_ADDRESS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ADDITIONAL_NUMBER_OF_SCORING" FLOAT(126) NOT NULL ENABLE, 
	"HOTEL_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE TABLE "SYSTEM"."REVIEWERS" 
   (	"REVIEWER_SCORE" FLOAT(126) NOT NULL ENABLE, 
	"REVIEWER_NATIONALITY" VARCHAR2(40 BYTE) NOT NULL ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
