SELECT DISTINCT HOTEL_NAME, COUNT(REVIEWER_SCORE)
FROM REVIEWERS, HOTEL
WHERE REVIEWER_SCORE > 5
GROUP BY hotel.hotel_name;

SELECT DISTINCT(REVIEWER_NATIONALITY),ROUND(COUNT(REVIEWER_NATIONALITY)/(SELECT COUNT(*) FROM REVIEWERS ),2)*100||'%' as PrecentOfNEGATIVE
FROM REVIEWERS
GROUP BY REVIEWER_NATIONALITY
ORDER BY PrecentOfNEGATIVE;


SELECT  REVIEW_DATE,REVIEWER_SCORE
FROM REVIEWERS, REVIEWS
order by REVIEW_DATE;

