SELECT REVIEWER_SCORE, REVIEWER_NATIONALITY, HOTEL_NAME 
FROM REVIEWERS, HOTEL 
WHERE REVIEWER_SCORE > 5;

SELECT HOTEL_NAME, AVERAGE_SCORE, REVIEWER_SCORE, ROUND(1 - REVIEWER_SCORE/AVERAGE_SCORE,2)*100||'%' as PrecentOfAVERAGE
FROM REVIEWERS, HOTEL,REVIEWS;

SELECT REVIEWER_SCORE, EXTRACT(MONTH FROM REVIEW_DATE) 
FROM REVIEWERS, REVIEWS
